 FROM node:22-alpine

 ARG  DATABASE_URL    
 
 WORKDIR  /usr/src/app

 RUN npm i -g pnpm 
 
 COPY ./package.json ./package.json
 COPY ./packages ./packages
 COPY ./turbo.json ./turbo.json
 COPY ./pnpm-lock.yaml  ./pnpm-lock.yaml
 COPY ./apps/web  ./apps/web
 
RUN pnpm install
RUN pnpm run generate:db
RUN DATABASE_URL=${DATABASE_URL} pnpm run build

CMD [ "pnpm","run","start:web" ]